<?php

namespace RecommandationTransceiverAntenna\Model;

use RecommandationTransceiverAntenna\Model\Base\RecommandationtransceiverantennaRecommandation as BaseRecommandationtransceiverantennaRecommandation;

class RecommandationtransceiverantennaRecommandation extends BaseRecommandationtransceiverantennaRecommandation
{

}
