<?php

namespace RecommandationTransceiverAntenna\Model;

use RecommandationTransceiverAntenna\Model\Base\Recommandationtransceiverantenna as BaseRecommandationtransceiverantenna;

class Recommandationtransceiverantenna extends BaseRecommandationtransceiverantenna
{

}
